FROM  public.ecr.aws/lambda/java:17

ADD target/babyzz-backend-1.0.0-SNAPSHOT-runner.jar /var/task/lib/babyzz-backend.jar
ADD target/lib/  /var/task/lib/

CMD ["io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest"]