version: "3"
services:
  mongo:
    image: mongo:4.4
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports: 
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      - mongo
    restart: on-failure

volumes:
    mongodbdata: